package com.harmonia.common.kafka;

public enum EventType {
    USER_REGISTERED,
    USER_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    TRACK_UPLOADED,
    TRACK_PUBLISHED,
    TRACK_UNPUBLISHED,
    TRACK_LIKED,
    TRACK_UNLIKED,
    PLAYLIST_CREATED,
    PLAYLIST_UPDATED,
    PLAYLIST_DELETED,
    TRACK_PLAYED,
    PLAYBACK_STARTED,
    PLAYBACK_COMPLETED,
    TRACK_SKIPPED,
    ARTIST_FOLLOWED,
    ARTIST_UNFOLLOWED,
    ALBUM_CREATED,
    ALBUM_PUBLISHED,
    SEARCH_PERFORMED,
    PLAYLIST_OPENED,
    ARTIST_OPENED,
    ALBUM_OPENED
}
