package com.harmonia.common.api.error;

public enum ErrorCode {
    VALIDATION_FAILED,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    RATE_LIMITED,
    BAD_REQUEST,
    INTERNAL_ERROR,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,
    EMAIL_NOT_VERIFIED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    REFRESH_TOKEN_INVALID,

    ARTIST_NOT_FOUND,
    ALBUM_NOT_FOUND,
    TRACK_NOT_FOUND,
    GENRE_NOT_FOUND,
    PLAYLIST_NOT_FOUND,
    PLAYLIST_NOT_OWNED,
    TRACK_ALREADY_IN_PLAYLIST,

    PLAYBACK_SESSION_NOT_FOUND,
    QUEUE_EMPTY,
    STORAGE_FAILURE,
    SEARCH_UNAVAILABLE,
    UPSTREAM_UNAVAILABLE
}
