global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: harmonia-host
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
          - host.docker.internal:8081
          - host.docker.internal:8082
          - host.docker.internal:8083
          - host.docker.internal:8084
          - host.docker.internal:8085
          - host.docker.internal:8086
          - host.docker.internal:8087
          - host.docker.internal:8088
          - host.docker.internal:8089
          - host.docker.internal:8761
          - host.docker.internal:8888
  - job_name: harmonia-compose
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway:8080
          - auth-service:8081
          - user-service:8082
          - catalog-service:8083
          - playlist-service:8084
          - playback-service:8085
          - search-service:8086
          - recommendation-service:8087
          - analytics-service:8088
          - notification-service:8089
          - eureka-server:8761
          - config-server:8888
