apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: harmonia
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: harmonia/catalog-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8083
          envFrom:
            - configMapRef:
                name: harmonia-config
            - secretRef:
                name: harmonia-secrets
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql.harmonia.svc.cluster.local:3306/harmonia_catalog?useSSL=false&allowPublicKeyRetrieval=true"
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: harmonia
  labels:
    app: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - name: http
      port: 8083
      targetPort: http
