apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: harmonia
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: harmonia/payment-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
          envFrom:
            - configMapRef:
                name: harmonia-config
            - secretRef:
                name: harmonia-secrets
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql.harmonia.svc.cluster.local:3306/harmonia_payment?useSSL=false&allowPublicKeyRetrieval=true"
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits: { cpu: 500m, memory: 512Mi }
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            initialDelaySeconds: 40
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: http }
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: harmonia
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8090
      targetPort: http
